name: Bring up Redis Sentinel Cluster
description: >-
  Installs docker-compose and runs Redis Sentinel cluster
  with ports 16379-16380 for redis and
  26379-26380 for sentinel
runs:
  using: composite
  steps:
    - name: Set up Docker Compose
      uses: docker/setup-compose-action@364cc21a5de5b1ee4a7f5f9d3fa374ce0ccde746

    - name: Run Sentinel cluster
      env:
        ACTION_PATH: ${{ github.action_path }}
      shell: bash
      run: |
        docker compose --file "${ACTION_PATH}/docker-compose.yml" up --detach --wait

    - name: Inspect failure
      if: always()
      shell: bash
      run: |
        echo "::group::Inspect failure - docker compose ps"
        cd ${{ github.action_path }}
        docker compose ps
        echo "::endgroup::"
        echo "::group::Inspect failure - docker compose logs"
        docker compose logs
        echo "::endgroup::"
        echo "::group::Inspect failure - sentinel"
        docker compose exec redis-master-1 redis-cli -p 26379 SENTINEL CKQUORUM hello || :
        docker compose exec redis-master-1 redis-cli -p 26379 SENTINEL CKQUORUM redis-sentry || :
        echo "::endgroup::"
